name: Tektra schedule

on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 minutos
  workflow_dispatch:          # también lo podés correr a mano

permissions:
  contents: write

jobs:
  run-tektra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pyyaml faker

      - name: Run orchestrator (3 items por ciclo)
        run: |
          python orchestrator.py --count 3

      - name: Commit outputs
        run: |
          git config user.name "tektra-bot"
          git config user.email "tektra@users.noreply.github.com"
          git add -A
          git commit -m "tektra: auto-run $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "Nada para commitear"
          git push
