name: Tektra schedule

on:
  schedule:
    - cron: "0 * * * *" # cada hora
  workflow_dispatch:

jobs:
  run-tektra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create output dir
        run: mkdir -p output

      - name: Run orchestrator (3 items por ciclo)
        run: python orchestrator.py

      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*
          git commit -m "Auto: add new Tektra outputs [skip ci]" || echo "No changes"
          git push
