name: maker-bot

on:
  push:
    branches: [ main ]          # corre en cada push a main
  workflow_dispatch:            # botón "Run workflow"
  schedule:
    - cron: "*/20 * * * *"      # cada 20 minutos

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # permitir commits automáticos
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity check
        run: |
          ls -la
          test -f config.yaml || (echo "❌ Falta config.yaml en la raíz" && exit 1)

      - name: Run orchestrator once (with timeout)
        run: |
          set -e
          echo "RUN_ONCE=$RUN_ONCE"
          timeout 90s python orchestrator.py
        env:
          RUN_ONCE: "1"         # fuerza una sola iteración en Actions

      - name: Commit outputs if changed
        run: |
          git config user.name "maker-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "bot: nuevos artefactos"
          git push
