name: Tektra schedule

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-tektra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create output dir
        run: mkdir -p output

      - name: Expose repo in PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Debug tree (find factories)
        run: |
          echo "=== FACTORY FILES FOUND ==="
          find . -maxdepth 4 -type f -name "*_factory.py" -print || true
          echo "==========================="

      - name: Run orchestrator (3 items por ciclo)
        run: python -u orchestrator.py

      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A output || true
          git commit -m "Tektra: auto outputs $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
          git push
