name: maker-bot

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: "*/20 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          echo -e "pyyaml\nflask" >> requirements.txt
          pip install -r requirements.txt || true

      - name: Sanity check
        run: |
          ls -la
          test -f orchestrator.py || (echo "❌ falta orchestrator.py en la raíz" && exit 1)
          test -f factories/__init__.py || (echo "❌ falta factories/__init__.py" && exit 1)
          if [ -f config.yaml ]; then echo "✅ config.yaml está"; else echo "⚠️ sin config.yaml (defaults)"; fi

      - name: Run orchestrator once (with timeout)
        env:
          RUN_ONCE: "1"
        run: |
          set -e
          timeout 90s python orchestrator.py

      - name: Commit outputs if changed
        run: |
          git config user.name "maker-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "bot: nuevos artefactos"
          git push
