name: Maker Bot (cron)

on:
  schedule:
    - cron: "*/30 * * * *"  # corre cada 30 minutos
  workflow_dispatch:

permissions:
  contents: write   # necesario para commit/push con GITHUB_TOKEN

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (tolerante)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          # Pillow opcional para PNG; si falla, el orquestador cae a SVG
          pip install pillow || true

      - name: Run orchestrator
        run: |
          python orchestrator.py

      - name: Commit & push changes (si los hay)
        env:
          TZ: America/Argentina/Buenos_Aires
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(bot): auto-run output update"
            # protegerse de conflictos de cron concurrentes
            git pull --rebase || true
            git push
          else
            echo "No hay cambios para commitear."
          fi
