name: maker-bot

on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 minutos
  workflow_dispatch:

permissions:
  contents: write   # NECESARIO para poder hacer git push

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0           # full history
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity check
        run: python -c "print('ok')"

      - name: Run orchestrator once (with timeout)
        working-directory: ${{ github.workspace }}
        run: |
          set -e
          echo "[maker-bot] usando config: ${{ github.workspace }}/config.yaml"
          python orchestrator.py

      - name: Commit outputs if changed
        working-directory: ${{ github.workspace }}
        env:
          TZ: UTC
        run: |
          set -e
          echo "Archivos cambiados:"
          git status --porcelain

          CHANGES=$(git status --porcelain -- output/ | wc -l)
          if [ "$CHANGES" -gt 0 ]; then
            git config user.name  "maker-bot"
            git config user.email "maker-bot@users.noreply.github.com"
            git add -A output/
            git commit -m "bot: nuevos artefactos"
            git push
            echo "✅ Cambios en output/ commiteados."
          else
            echo "ℹ️ No hay cambios en output/."
          fi
